baseurl = "https://idiotblogs.netlify.app/"
title = "IdiotCodes"
theme = "PaperMod"

[Params]
    mainSections = ["post"]
    github = "https://github.com/idiotcodes"
    twitter = "https://twitter.com/idiotcodes"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
